# Generated by Django 2.2.2 on 2019-07-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='naiyo',
            field=models.CharField(max_length=30, unique=True, verbose_name='内容名'),
        ),
        migrations.AlterField(
            model_name='division',
            name='kubun',
            field=models.CharField(max_length=30, unique=True, verbose_name='区分名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='ユーザー名'),
        ),
    ]
